### ISSUE TITLE
Percentage values might be in their wrong decimal places

### ISSUE THREAD

**Issue by ruchern** [krestaino/weather-vue#17]
The percentage for cloud cover, precipitation and humidity could potentially be wrong. The decimal place looks a little off.

**Comment by krestaino** [comment]
What is the search query you're experiencing this with?

**Comment by ruchern** [comment]
<img width="1280" alt="screen shot 2017-05-15 at 1 00 01 am" src="https://cloud.githubusercontent.com/assets/10343662/26036082/de1ccf28-3909-11e7-8f0f-16870117ad7d.png">

See screenshot as attached. I have also highlighted the error in the picture.

**Comment by krestaino** [comment]
Ah, I see what you mean. Good catch! Thank you.

**Comment by ruchern** [comment]
I was looking at using the `computed()` method to display the percentages, but 8f3408aff9f6b73ef390c207641f83dadb701ce3 was a quick and simple fix.
