### ISSUE TITLE
Geolocation API is not working.

### ISSUE THREAD

**Issue by ruchern** [krestaino/weather-vue#20]
<img width="1280" alt="screen shot 2017-05-15 at 8 22 32 am" src="https://cloud.githubusercontent.com/assets/10343662/26039015/ac98e0a2-3947-11e7-94f2-3a283536c0f3.png">
Having issue with the API at the moment, which exact API did you use from Google? I tried various ones from Google Maps Javascript API to Google Maps Geolocation and nothing works.

My API looks like this: AIzaSyB_XXXXXXXXXXXXX. Is yours similar?

**Comment by krestaino** [comment]
Have you cloned [this ](https://github.com/krestaino/weather-api)repo and started the server? That's the backend portion of this weather app and needs to be running at the same time.

**Comment by ruchern** [comment]
@krestaino No I did not. I guess that should fix the problem. Dam, I thought the API server is already running from your web service.

**Comment by ruchern** [comment]
Probably fixed with #21
