### ISSUE TITLE
Geolocation is not working in Safari 10.1

### ISSUE THREAD

**Issue by ruchern** [krestaino/weather-vue#28]
**OS Version:** macOS 10.12.5
**Browser Version:** Safari 10.1

### Issue:
Geolocation is not being prompted on Safari 10.1

### How to reproduce:
Just load the page and there was no prompt.

**Comment by krestaino** [comment]
I believe this is because Safari requires HTTPS for geolocation. If you check the live site, https://weather.kmr.io, it works fine in Safari. Going to close this.

**Comment by ruchern** [comment]
Yeah you're right. It does seem to require HTTPS.
