### ISSUE TITLE
Animate maps in background on location change

### ISSUE THREAD

**Issue by ruchern** [krestaino/weather-vue#31]
The maps in the background seems to be flashing right now.

**Comment by krestaino** [comment]
I think I've figured out how to reproduce this. It's when using the browser geolocation. When searching, I don't get the flicker. Once I click the geolocation button, or load the app for the first time and let the it use geolocation, I see the double flicker. Can you confirm?

I think I know what's going on and can issue a fix for this.

**Comment by ruchern** [comment]
I cannot reproduce it at the moment, it could just be slow internet which is "downloading" the map in the background.
